import JSZip from 'jszip';
import { ConvertedArt, PixelArtSettings } from '../types';

export interface CommandOptions {
  coordinateType: 'relative' | 'absolute';
  startX: number;
  startY: number;
  startZ: number;
  orientation: 'horizontal' | 'vertical'; // floor or wall
  replaceMode: 'replace' | 'keep' | 'destroy';
}

export function generateMinecraftCommands(
  art: ConvertedArt,
  options: CommandOptions
): string {
  const { width, height, grid, blockPalette } = art;
  const { coordinateType, startX, startY, startZ, orientation, replaceMode } = options;

  const lines: string[] = [
    `# Minecraft Pixel Art Commands`,
    `# Dimensions: ${width} x ${height} (${art.totalBlocks} blocks)`,
    `# Orientation: ${orientation === 'horizontal' ? 'Horizontal (Floor/Map)' : 'Vertical (Wall/Billboard)'}`,
    `# Generated by Minecraft Pixel Art Generator`,
    ``,
  ];

  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const blockIdx = grid[y][x];
      const block = blockPalette[blockIdx];
      if (!block) continue;

      let posXStr = '';
      let posYStr = '';
      let posZStr = '';

      if (orientation === 'horizontal') {
        // Built on floor (X and Z, flat at Y)
        if (coordinateType === 'relative') {
          posXStr = x === 0 ? '~' : `~${x}`;
          posYStr = '~';
          posZStr = y === 0 ? '~' : `~${y}`;
        } else {
          posXStr = `${startX + x}`;
          posYStr = `${startY}`;
          posZStr = `${startZ + y}`;
        }
      } else {
        // Built upright on wall (X and Y, flat at Z)
        // Note: Pixel art y=0 is top, in Minecraft Y increases upwards
        const invertedY = height - 1 - y;
        if (coordinateType === 'relative') {
          posXStr = x === 0 ? '~' : `~${x}`;
          posYStr = invertedY === 0 ? '~' : `~${invertedY}`;
          posZStr = '~';
        } else {
          posXStr = `${startX + x}`;
          posYStr = `${startY + invertedY}`;
          posZStr = `${startZ}`;
        }
      }

      lines.push(`setblock ${posXStr} ${posYStr} ${posZStr} ${block.commandName} ${replaceMode}`);
    }
  }

  return lines.join('\n');
}

export async function createDatapackZip(
  art: ConvertedArt,
  settings: PixelArtSettings,
  commands: string
): Promise<Blob> {
  const zip = new JSZip();

  // Function file
  zip.file('minecraft_pixel_art.mcfunction', commands);

  // Material list text
  const materialLines = [
    `MINECRAFT PIXEL ART MATERIAL BILL`,
    `================================`,
    `Total Blocks: ${art.totalBlocks.toLocaleString()}`,
    `Dimensions: ${art.width} wide x ${art.height} high`,
    ``,
    `ITEM BREAKDOWN:`,
  ];

  const sorted = Object.entries(art.counts).sort((a, b) => b[1] - a[1]);
  for (const [id, count] of sorted) {
    const block = art.blockPalette.find((b) => b.id === id);
    const name = block ? block.name : id;
    const stacks = Math.floor(count / 64);
    const rem = count % 64;
    const stackText = stacks > 0 ? `${stacks} stack${stacks > 1 ? 's' : ''} + ${rem}` : `${rem}`;
    materialLines.push(`- ${name.padEnd(28)} : ${count.toString().padStart(5)} (${stackText} items)`);
  }

  zip.file('materials_needed.txt', materialLines.join('\n'));

  // README with instructions
  const readme = `HOW TO RUN THIS IN MINECRAFT:
------------------------------------------
OPTION 1: In-game Function Datapack (Easiest for large builds):
1. Open your Minecraft world folder (saves/<world_name>).
2. Go to datapacks/ -> create a folder named "pixelart".
3. Inside "pixelart", create "pack.mcmeta":
   {"pack":{"pack_format":48,"description":"Pixel Art Datapack"}}
4. Create folder path: "data/pixelart/function/".
5. Put "minecraft_pixel_art.mcfunction" inside that function folder.
6. In game, type: /reload
7. Stand where you want the bottom-left corner to be and run:
   /function pixelart:minecraft_pixel_art

OPTION 2: Command Block / Chat (For small builds under 100 blocks):
- Copy the commands and paste into command blocks set to "Always Active".
`;
  zip.file('README_HOW_TO_USE.txt', readme);

  return await zip.generateAsync({ type: 'blob' });
}
